apiVersion: v1
kind: Namespace
metadata:
  name: backend-estabelecimento
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::975049952960:role/LabRole
  name: backend-estabelecimento-serviceaccount
  namespace: backend-estabelecimento
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-estabelecimento-hpa
  namespace: backend-estabelecimento
  labels:
    app.kubernetes.io/name: backend-estabelecimento
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-estabelecimento-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 65
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-estabelecimento-app
  namespace: backend-estabelecimento
  labels:
    app.kubernetes.io/name: backend-estabelecimento-app
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: backend-estabelecimento-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend-estabelecimento-app
    spec:
      serviceAccountName: backend-estabelecimento-serviceaccount
      containers:
        - name: backend-estabelecimento-app
          image: leodelmiro/fiap-estabelecimento:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "256m"
              memory: "512M"
            limits:
              cpu: "512m"
              memory: "2048M"
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-estabelecimento-configmap
                  key: db_url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: backend-estabelecimento-configmap
                  key: db_username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-estabelecimento-configmap
                  key: db_password
            - name: MERCADO_PAGO_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-estabelecimento-configmap
                  key: mercado_pago_url
            - name: MERCADO_PAGO_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: backend-estabelecimento-configmap
                  key: mercado_pago_token
          ports:
            - name: http-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-port
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http-port
            initialDelaySeconds: 240
            periodSeconds: 15
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-estabelecimento-svc
  namespace: backend-estabelecimento
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: backend-estabelecimento-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-estabelecimento-configmap
  namespace: backend-estabelecimento
data:
  db_url: jdbc:postgresql://estabelecimento.cxhd5ilcfd6d.us-east-1.rds.amazonaws.com:5432/estabelecimento
  db_username: "postgres"
  db_password: "12345678"
  mercado_pago_url: "https://api.mercadopago.com/"
  mercado_pago_token: "TEST-3657452763101763-100208-0446e47cd6850436418091b63a34c651-827114336"