apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-pedido-configmap
  namespace: backend-estabelecimento
data:
  mercado_pago_url: "https://api.mercadopago.com/"
  mercado_pago_token: "TEST-3657452763101763-100208-0446e47cd6850436418091b63a34c651-827114336"