apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-pedido-configmap
  namespace: backend-estabelecimento
data:
  db_url: jdbc:postgresql://pedido.cf4grgsaa5x0.us-east-1.rds.amazonaws.com:5432/pedido
  db_username: "postgres"
  db_password: "12345678"
  sqs_url: "https://sqs.us-east-1.amazonaws.com"
  cliente_url: "http://ALB-cliente-80364347.us-east-1.elb.amazonaws.com/api/v1"
  produto_url: "http://ALB-produto-1341275448.us-east-1.elb.amazonaws.com/api/v1"
  pagamento_url: "http://ALB-pagamento-1037929076.us-east-1.elb.amazonaws.com/api/v1"
  aws_access_key: "{{AWS_ACCESS_KEY_ID}}"
  aws_secret_key: "{{AWS_SECRET_ACCESS_KEY}}"
  aws_session_token: "{{AWS_SESSION_TOKEN}}"