apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-pedido-configmap
  namespace: backend-estabelecimento
data:
  db_url: jdbc:postgresql://pedido.cpmueqg0y0dn.us-east-1.rds.amazonaws.com:5432/pedido
  db_username: "postgres"
  db_password: "12345678"
  cliente_url: "https://cliente.com/"
  produto_url: "https://produto.com/"
  pagamento_url: "https://pagamento.com/"