name: 3 - [DEVELOP] PR & Plan

on:
  pull_request:
    types:
      - "closed"
    branches:
      - "develop"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Terraform Init and Plan
        id: plan
        shell: bash
        run: |
          cd infra/terraform
          terraform init
          terraform plan -no-color -out=tfplan
          echo 'plan<<EOF' >> $GITHUB_OUTPUT
          terraform show -no-color tfplan >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/terraform/tfplan
          overwrite: true
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          gh_pr_up() { gh pr create "$@" || gh pr edit "$@" ; }
          gh_pr_up --title "Develop para main" --base "main" --body "$(cat <<EOF
            Terraform Plan:
          
            ```
            ${{ steps.plan.outputs.plan }}
            ```

            Plan salvo no GH artifacts.
          EOF
          )"